# fly.toml app configuration file generated for e-whisper-tailwings on 2023-12-01T14:49:36+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "e-whisper-tailwings"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[env]
  PORT = "41641"

[http_service]
  internal_port = 41641
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "udp"
  internal_port = 41641
  processes = ["app"]

  [[services.ports]]
    port = 41641
  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 75

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
